# Generated by Django 3.0 on 2021-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='test summary', max_length=200),
            preserve_default=False,
        ),
    ]
